using Abp.Domain.Entities;
using System;
using System.Collections.Generic;

namespace VisitorSystem.VisitorsSystem.OASystem
{
    public partial class HrmResource : Entity
    {
        public string Loginid { get; set; }
        public string Password { get; set; }
        public string Lastname { get; set; }
        public string Sex { get; set; }
        public string Birthday { get; set; }
        public int? Nationality { get; set; }
        public int? Systemlanguage { get; set; }
        public string Maritalstatus { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Mobilecall { get; set; }
        public string Email { get; set; }
        public int? Locationid { get; set; }
        public string Workroom { get; set; }
        public string Homeaddress { get; set; }
        public string Resourcetype { get; set; }
        public string Startdate { get; set; }
        public string Enddate { get; set; }
        public int? Jobtitle { get; set; }
        public string Jobactivitydesc { get; set; }
        public int? Joblevel { get; set; }
        public int? Seclevel { get; set; }
        public int? Departmentid { get; set; }
        public int? Subcompanyid1 { get; set; }
        public int? Costcenterid { get; set; }
        public int? Managerid { get; set; }
        public int? Assistantid { get; set; }
        public int? Bankid1 { get; set; }
        public string Accountid1 { get; set; }
        public int? Resourceimageid { get; set; }
        public int? Createrid { get; set; }
        public string Createdate { get; set; }
        public int? Lastmodid { get; set; }
        public string Lastmoddate { get; set; }
        public string Lastlogindate { get; set; }
        public string Datefield1 { get; set; }
        public string Datefield2 { get; set; }
        public string Datefield3 { get; set; }
        public string Datefield4 { get; set; }
        public string Datefield5 { get; set; }
        public double? Numberfield1 { get; set; }
        public double? Numberfield2 { get; set; }
        public double? Numberfield3 { get; set; }
        public double? Numberfield4 { get; set; }
        public double? Numberfield5 { get; set; }
        public string Textfield1 { get; set; }
        public string Textfield2 { get; set; }
        public string Textfield3 { get; set; }
        public string Textfield4 { get; set; }
        public string Textfield5 { get; set; }
        public byte? Tinyintfield1 { get; set; }
        public byte? Tinyintfield2 { get; set; }
        public byte? Tinyintfield3 { get; set; }
        public byte? Tinyintfield4 { get; set; }
        public byte? Tinyintfield5 { get; set; }
        public string Certificatenum { get; set; }
        public string Nativeplace { get; set; }
        public int? Educationlevel { get; set; }
        public string Bememberdate { get; set; }
        public string Bepartydate { get; set; }
        public string Workcode { get; set; }
        public string Regresidentplace { get; set; }
        public string Healthinfo { get; set; }
        public string Residentplace { get; set; }
        public string Policy { get; set; }
        public string Degree { get; set; }
        public string Height { get; set; }
        public int? Usekind { get; set; }
        public int? Jobcall { get; set; }
        public string Accumfundaccount { get; set; }
        public string Birthplace { get; set; }
        public string Folk { get; set; }
        public string Residentphone { get; set; }
        public string Residentpostcode { get; set; }
        public string Extphone { get; set; }
        public string Managerstr { get; set; }
        public int? Status { get; set; }
        public string Fax { get; set; }
        public string Islabouunion { get; set; }
        public int? Weight { get; set; }
        public string Tempresidentnumber { get; set; }
        public string Probationenddate { get; set; }
        public int? Countryid { get; set; }
        public string Passwdchgdate { get; set; }
        public int? Needusb { get; set; }
        public string Serial { get; set; }
        public string Account { get; set; }
        public string Lloginid { get; set; }
        public int? Needdynapass { get; set; }
        public double? Dsporder { get; set; }
        public int? Passwordstate { get; set; }
        public int? Accounttype { get; set; }
        public int? Belongto { get; set; }
        public string Dactylogram { get; set; }
        public string Assistantdactylogram { get; set; }
        public int? Passwordlock { get; set; }
        public int? Sumpasswordwrong { get; set; }
        public string Oldpassword1 { get; set; }
        public string Oldpassword2 { get; set; }
        public string MsgStyle { get; set; }
        public string Messagerurl { get; set; }
        public string Pinyinlastname { get; set; }
        public string Tokenkey { get; set; }
        public string UserUsbType { get; set; }
        public string Outkey { get; set; }
        public string Adsjgs { get; set; }
        public string Adgs { get; set; }
        public string Adbm { get; set; }
        public int? Mobileshowtype { get; set; }
        public int? Usbstate { get; set; }
        public double? TotalSpace { get; set; }
        public double? OccupySpace { get; set; }
        public string EcologyPinyinSearch { get; set; }
        public string IsAdaccount { get; set; }
        public string Accountname { get; set; }
        public int? Notallot { get; set; }
        public int? Beforefrozen { get; set; }
        public string Resourcefrom { get; set; }
        public string Isnewuser { get; set; }
        public string Haschangepwd { get; set; }
        public DateTime? Created { get; set; }
        public int? Creater { get; set; }
        public DateTime? Modified { get; set; }
        public int? Modifier { get; set; }
        public DateTime? Passwordlocktime { get; set; }
        public string Mobilecaflag { get; set; }
        public string Salt { get; set; }
        public string Companystartdate { get; set; }
        public string Workstartdate { get; set; }
        public string SecondaryPwd { get; set; }
        public int? UseSecondaryPwd { get; set; }
        public string Classification { get; set; }
        public string Uuid { get; set; }
        public string PasswordLockReason { get; set; }
        public decimal? Companyworkyear { get; set; }
        public decimal? Workyear { get; set; }
        public string Dismissdate { get; set; }
    }
}
